[package]
name = "sudoku-sos-solver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = "0.7.2"
serde = { version = "1.0.164", features = ["derive"] }
